TOTAL_TIMESTEPS: 100000
PARAM: 0.00001
ALGO: "OURS"
DEVICE: "cuda:2"
ENV_NAME: "LunarLander-v3"
seed: 1

# EXP_NAME: "thesis/test_0_entropy"
EXP_NAME: "ecml/${ENV_NAME}-${ALGO}-${PARAM}-sb3hyperparams_nf"
# EXP_NAME: 'test-discriminantneg_1e-'

policy_kwargs:
  use_sde: True

ours_policy_kwargs:
  use_sde: False
  pi_be_ratio: 0.2
  pi_b_nf: True
ablation_mode: False

sb3_hyperparams: False

check_anomaly: True # checks if any non-finite values appear in torch backward()


hydra:
  run:
    dir: ./runs/${EXP_NAME}
