TOTAL_TIMESTEPS: 10000
PARAM: 1
ALGO: "OURS"
DEVICE: "cuda:2"
ENV_NAME: "AbsEnv-v0"
seed: 1

# EXP_NAME: "redo-long-${ENV_NAME}-${ALGO}-${PARAM}_nf"
EXP_NAME: "neural_spline_1_test"


policy_kwargs:
  use_sde: True

ours_policy_kwargs:
  use_sde: False
  pi_be_ratio: 0
  pi_b_nf: True
ablation_mode: False


hydra:
  run:
    dir: ./runs/${EXP_NAME}
