TOTAL_TIMESTEPS: 500000
PARAM: 0.1
ALGO: "OURS"
DEVICE: "cuda:2"
ENV_NAME: "BipedalWalker-v3"
seed: 1

EXP_NAME: "thesis/${ENV_NAME}-${ALGO}-adv-${PARAM}_nf"


policy_kwargs:
  use_sde: True

ours_policy_kwargs:
  use_sde: False
  pi_be_ratio: 0
  pi_b_nf: True
ablation_mode: False


hydra:
  run:
    dir: ./runs/${EXP_NAME}
