TOTAL_TIMESTEPS: 500000
PARAM: 0.0
ALGO: "OURS"
DEVICE: "cuda:0"
ENV_NAME: "BipedalWalker-v3"
seed: 1

EXP_NAME: "thesis/${ENV_NAME}-${ALGO}-sb3hyperparams_nf"


policy_kwargs:
  use_sde: True

ours_policy_kwargs:
  use_sde: False
  pi_be_ratio: 0
  pi_b_nf: False
ablation_mode: False

sb3_hyperparams: False


hydra:
  run:
    dir: ./runs/${EXP_NAME}
