TOTAL_TIMESTEPS: 1000000
ALGO: "OURS"
DEVICE: "cuda:2"
ENV_NAME: "Swimmer-v5"
seed: 1

hyperparams:
  ent_coef: 0.00001
  gamma: 0.9

ours_policy_kwargs:
  use_sde: False
  pi_be_ratio: 0.2
  pi_b_nf: True
  num_flows: 4
  ablation_mode: False

check_anomaly: False # checks if any non-finite values appear in torch backward()

# to allow appending to exp_name
_EXP_NAME: "ecml/${now:%Y%m%d_%H%M}_${ENV_NAME}-${ALGO}"
EXP_NAME: "${EXP_NAME}"

hydra:
  run:
    dir: ./runs/${EXP_NAME}
